// This file is generated by npm run build:icons

export type IconName =
	| "phosphor-icons/chart-line"
	| "phosphor-icons/fire"
	| "radix-icons/chevron-down"
	| "radix-icons/chevron-right"
	| "radix-icons/clock"
	| "radix-icons/external-link"
	| "radix-icons/gear"
	| "radix-icons/question-mark-circled";
